# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 951bdf05f8d79003e9abc09ceb804ba7c927283a69f922e8fdebc26dc9f0ac0116dee97b9233cfc2c574e6ae7d86202a7ba95b74e1068a76d675d0106af76749

test:
  secret_key_base: e992f1f462931e4404aa80b3504d8a997c3682d80fac1f969731152eef87597d2fc6c80aa172b5b7201d31d386de41a0b977193c4fc98f1e1867b9c8cfeb1d2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
